apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  labels:
    event-enabled-insurance.eei.canvas: 'true'
    eventstreams.ibm.com/cluster: eeikafka
  name: claim-status-producer
  namespace: eei
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - operations:
          - Read
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - operations:
          - Read
          - Write
          - Create
          - Delete
          - Alter
          - Describe
          - All
        resource:
          name: claimstatus
          type: topic
    type: simple
