apiVersion: apiconnect.ibm.com/v1beta1
kind: Product
metadata:
  labels:
    backup.apiconnect.ibm.com/component: product
    event-enabled-insurance.eei.canvas: 'true'
  name: eei-claim-product
  namespace: eei
spec:
  apis:
    integrationRuntimes:
      - name: claimsapi
  definition:
    info:
      description: EEI Demo Product
      name: eei-claim-product
      summary: EEI Demo Product
      title: This is the EEI demo
      version: '1.0'
    plans:
      default-plan:
        approval: false
        description: Default Plan
        rate-limits:
          default:
            value: 100/1hour
        title: Default Plan
    product: 1.0.0
  share:
    apim:
      catalog: main-demo-catalog
      credentialsSecret: apim-credentials
      providerOrg: main-demo
  state: Published
